Schools archive
znick/anytask pull request #347
Opened 2021-03-06 15:59 UTC by houcha

#335

Один момент: в текущей конфигурации архивированная школа может иметь активные курсы. С логической точки зрения это плохо, и есть пара вариантов, что с этим можно сделать:
1. При архивации школы помечать все её курсы архивированными. Однако по-прежднему остаётся возможность руками перетащить курсы в "активные". Хорошим (на первый взгляд) решением будет сделать отдельную страницу для архивированных школ, в которой нет кнопок "активные курсы" и "архив". Выглядеть это будет, конечно, правильно, но с точки зрения бека проблему не решает (is_active всё ещё подвержен изменениям), да и выглядит как костыль.
2. Оставить всё как есть - пусть админ сам следит :)

Не знаю, насколько это важно, но на всякий случай хочу узнать мнение.

2021-03-06 18:22 UTC, znick commented
Выглядит неплохо, но нужны еще тесты.

Нужно написать простые тесты:
1. Если школа активная, то он есть на главной странице и его нет в архиве.
2. Если школа неактивная, то наоборот.

2021-03-07 14:17 UTC, znick requested changes

2021-03-07 14:17 UTC, znick commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
```suggestion
    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=True)
```

2021-03-07 14:17 UTC, znick commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
Извини, сразу не заметил. Давай default=True сделаем тут. Иначе при раскатке обновления у нас все текущие школы станут неактивными.

Тебе придется перегенерить миграцию :(

2021-03-07 14:17 UTC, znick commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
Отсальное ok

2021-03-07 16:25 UTC, houcha commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
Звучит разумно.
Вообще я это поле просто честно из класса Course скопировал. Там умышленно false стоит? Мол, сперва черновой вариант курса делаем, и только потом открываем.
А что имеется в виду под обновлениями? В доках сказано: The default value is used when new model instances are created and a value isn’t provided for the field. Обновления как-то связаны с созданием объектов? Я считал, что они про кодовую базу.

2021-03-07 18:40 UTC, znick commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
>Вообще я это поле просто честно из класса Course скопировал. Там умышленно false стоит? Мол, сперва черновой вариант курса делаем, и только потом открываем.

Да, там это поле было всегда или почти всегда, поэтому такой проблемы нет. При создании курса галочку можно поставить - не проблема.

Со школами сейчас проблема будет с уже существующими школами.

>А что имеется в виду под обновлениями? В доках сказано: The default value is used when new model instances are created and a value isn’t provided for the field. Обновления как-то связаны с созданием объектов? Я считал, что они про кодовую базу.

Когда будет наказываться миграция, то для все существующих школ будет выставлено дефолтное значение поля (потому что null=False).

В целом, конечно, ничего страшного, но не хотелось бы после обновления бегом бежать проставлять галочки :)

2021-03-07 18:41 UTC, znick approved these changes

2021-03-07 18:41 UTC, merged

2021-03-07 19:51 UTC, houcha commented on anytask/schools/models.py
> +    is_active = models.BooleanField(db_index=True, null=False, blank=False, default=False)
Понял, спасибо.